### ISSUE TITLE
Error when i install

### ISSUE THREAD

**Issue by ElBidouilleur** [veged/coa#101]
HI

When I update all package in my project 

`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coa@2.1.3 preinstall: start /B node compile.js & node compile.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coa@2.1.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mboutin/.npm/_logs/2021-11-04T14_01_45_544Z-debug.log
`

**Comment by okkindel** [comment]
duplicate https://github.com/veged/coa/issues/99

**Comment by mizhon** [comment]
Get the same error when I saw the new version was published. 
![image](https://user-images.githubusercontent.com/6859933/140331520-9439cf67-5944-460d-be18-84479d4ec130.png)

And now I find they fix it.
![image](https://user-images.githubusercontent.com/6859933/140332185-89958669-41aa-414d-b7d5-4b24c765cf1c.png)

**Comment by color-me** [comment]
Same question

**Comment by ShenganLee** [comment]
Same question

**Comment by bhdr1** [comment]
After three years?? :/

**Comment by jacksaad1991** [comment]
I don't see this removal that @mizhon has mentioned, when i go to NPM I still see it like this:
![Screenshot 2021-11-04 at 15 16 36](https://user-images.githubusercontent.com/81391626/140345478-f0c1e63f-52b4-4520-83de-e36c7ef5bd7b.png)

**Comment by wuyuchang** [comment]
The author has deleted the package.

**Comment by wuyuchang** [comment]
> Get the same error when I saw the new version was published. ![image](https://user-images.githubusercontent.com/6859933/140331520-9439cf67-5944-460d-be18-84479d4ec130.png)
> 
> And now I find they fix it. ![image](https://user-images.githubusercontent.com/6859933/140332185-89958669-41aa-414d-b7d5-4b24c765cf1c.png)

npm install coa@2.0.2
and make sure that package.json doesn't have ^ in front of the version. package-lock.json will be better

**Comment by ihsanakcali** [comment]
is there any way to publish new version of this dependency?

**Comment by ihsanakcali** [comment]
i need new version because 2.1.3 corrupted and it was latest of major 2

**Comment by yarastqt** [comment]
@crashday Hello, currently latest version is `2.0.2`, you can check via npm cli:

```
λ ~ npm info coa

coa@2.0.2 | MIT | deps: 3 | versions: 29
Command-Option-Argument: Yet another parser for command line options.
http://github.com/veged/coa

dist
.tarball: https://registry.npmjs.org/coa/-/coa-2.0.2.tgz
.shasum: 43f6c21151b4ef2bf57187db0d73de229e3e7ec3
.integrity: sha512-q5/jG+YQnSy4nRTV4F7lPepBJZ8qBNJJDBuJdoejDyLXgmL7IEo+Le2JDZudFTFt7mrCqIRaSjws4ygRCTCAXA==
.unpackedSize: 72.5 kB

dependencies:
@types/q: ^1.5.1 chalk: ^2.4.1    q: ^1.1.2

maintainers:
- qfox <dazper88@protonmail.com>

dist-tags:
latest: 2.0.2

published over a year ago by qfox <zxqfox@gmail.com>
```

UPD. If you see another version, you can try to clean cache: `npm cache clean --force`

**Comment by ihsanakcali** [comment]
Hi @yarastqt, thank you. 
i use private nexus npm-proxy registry and it indexed coa 3.01 and 2.1.3. Everytime i try to build new package on CI/CD pipeline it fails because it tries to pull coa 2.1.3

**Comment by FeSeason** [comment]
Deleting packages is not a good way. They will be cached in internal nodes, such as verdaccio and nexus. It is recommended to upgrade directly

**Comment by ladieman217** [comment]
how to sync coa with verdaccio ?

**Comment by zhuCheer** [comment]
Get the same error

**Comment by tcstory** [comment]
same error

**Comment by ladieman217** [comment]
@FeSeason For using verdaccio, just manual remove coa in storage folder fix this problem.

**Comment by FeSeason** [comment]
> @FeSeason For using verdaccio, just manual remove coa in storage folder fix this problem.

already did.

**Comment by ihsanakcali** [comment]
2.1.3 removed but it is still in the index https://registry.npmjs.org/coa , who can fix it?

**Comment by marcorosa** [comment]
Some versions of this package have been removed because they contained malicious code. [More context here](https://github.com/advisories/GHSA-73qr-pfmq-6rp8).

**Comment by ihsanakcali** [comment]
i managed to update my npm proxy index with npm dist-tag coa command, my problem solved

**Comment by darioseidl** [comment]
I was getting an error too when I run yarn install, on a project that indirectly depends on coa@^2.0.2.

```
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/coa/-/coa-2.0.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/dario/Projekte/MediPrime/mp/mp-ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I can work around this issue, by putting 
```
  "resolutions": {
    "coa": "2.0.2"
  }
```
in my package.json.

It seems that version 2.0.4 was deleted from the npm and yarn repos because it contained malicious code. To solve resolutions of the ^2.0.2 range, a real fix would be to upload a proper version in that range, e.g. a 2.0.5 (even if it's the same code as 2.0.2). And a 2.1.4 for the removed 2.1.3 respectively.

**Comment by avtokey** [comment]
I have same error on Angular project, Can everyone tell me fix way ? "resolutions" and other solutions doesn't works

**Comment by darioseidl** [comment]
@avtokey Are you using npm or yarn (or something else)? Do you have a direct dependency on coa in your package.json or just some other package that depends on coa? What error do you get exactly?

**Comment by latel** [comment]
> I was getting an error too when I run yarn install, on a project that indirectly depends on coa@^2.0.2.
> 
> ```
> yarn install v1.22.10
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/coa/-/coa-2.0.4.tgz: Request failed \"404 Not Found\"".
> info If you think this is a bug, please open a bug report with the information provided in "/home/dario/Projekte/MediPrime/mp/mp-ui/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> 
> I can work around this issue, by putting
> 
> ```
>   "resolutions": {
>     "coa": "2.0.2"
>   }
> ```
> 
> in my package.json.
> 
> It seems that version 2.0.4 was deleted from the npm and yarn repos because it contained malicious code. To solve resolutions of the ^2.0.2 range, a real fix would be to upload a proper version in that range, e.g. a 2.0.5 (even if it's the same code as 2.0.2). And a 2.1.4 for the removed 2.1.3 respectively.

```
"resolutions": {
    "coa": "2.0.2"
  }
```
solves the problem, no idea which package is depending on coa-2.1.3

**Comment by tianfengbiao** [comment]
same problem

**Comment by avtokey** [comment]
@darioseidl Yes, I use NPM,  I don't have direct reference on my pckage.json, It seems some other package needs COA. Error: 404 Not Found - coa-2.1.3.tgz

**Comment by darioseidl** [comment]
With yarn you can use `yarn why coa` to find out which package depends on it, and yarn supports `resolutions` in the package.json.

npm doesn't have either, but you can try with third-party packages: [npm-why](https://github.com/amio/npm-why) and [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions). I haven't tried them myself, but they sound like the right thing for the job.
