### ISSUE TITLE
Don't include test directory in production

### ISSUE THREAD

**Issue by sotojuan** [veged/coa#60]
There's no reason to have the `test` and `tests` directories in production through `npm install`. It's wasteful! You can ignore them easily through an `.npmignore` file or whitelisting files in the `package.json`. I can do both as a PR if you want.

**Comment by arikon** [comment]
@sotojuan Make a PR, please

**Comment by zxqfox** [comment]
Whitelisting files is preferred ;-)

**Comment by sotojuan** [comment]
Done!
