### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by shyndman** [veged/coa#64]
Hi there,

We were wondering if you might consider adding one so that we can use your package. Thanks!

**Comment by aCandidMind** [comment]
Same here. It's problematic for license departments if they don't see a LICENSE file in the root containing a copyright statement as well or at least have that info in the README to see it in GitHub directly. But of course I know this is Open Source and so I created Pull Request #79.

**Comment by zxqfox** [comment]
Fellows, sorry for delay. and ty for your contribution!

PR was merged and will be published as 1.0.3 at this or the next week.

**Comment by zxqfox** [comment]
Closed in #80
