### ISSUE TITLE
Incorrect Termination Code

### ISSUE THREAD

**Issue by bdkjones** [veged/coa#85]
I dunno who's at fault for this one. SVGO depends on COA, but when you use COA 1.0.2 the termination code for `svgo -v` at the command line is incorrect, which breaks integration with other tools. When you use COA 1.0.1, it works just fine. I'm looping you in so somebody can figure out what's up. 

See: https://github.com/svg/svgo/issues/739

**Comment by zxqfox** [comment]
Thanks for reporting. Feels like it's fixed in master but not released...
I'm making a couple of tests right now.

**Comment by zxqfox** [comment]
Thanks again. Should be fixed in v1.0.3.
Let me know if something goes wrong.
